name: Build and Push DEV API Container to ECR

on:
  push:
    branches:
      - master
    # paths:
    #   - "api/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Habilita OpenID Connect
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Build Docker Image
        run: |
          cd api
          docker build -t repsell-api:latest . -f Dockerfile.prod

      - name: Tag Docker Image
        run: |
          docker tag respsell-internacional-api:latest public.ecr.aws/d0z6z8b6/respsell-internacional-api:latest

      - name: Push Docker Image to ECR
        run: |
          docker push public.ecr.aws/d0z6z8b6/respsell-internacional-api:latest